config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  attribute :date, :date, default: Date.new(2018, 1, 5)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_idea_form, only: [:new, :edit, :create, :update]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
  end

  # GET /ideas/1/edit
  def edit
    @idea_form.prefill_with(@idea)
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new

    respond_to do |format|
      if @idea_form.apply(params, to: @idea)
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea_form.apply(params, to: @idea)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def set_idea_form
      @idea_form = IdeaForm.new(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Render a form object as a form
  #
  # You can provide all options you provide to form_with
  def render_form(form_object, **options)
    form_with(model: form_object, **options) do |form|
      render(partial: form_object, as: :form_object, locals: { form: form })
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/fields/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.count, "error") %> prohibited this <%= model_name.human(count: 1) %> from being saved:</h2>

    <ul>
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/fields/_number_field.html.erb
<%= form.label(field.name) %>
<%= form.number_field(field.name, field.html_options) %>

app/views/fields/_text_area.html.erb
<%= form.label(field.name) %>
<%= form.text_area(field.name, field.html_options) %>

app/views/fields/_text_field.html.erb
<%= form.label(field.name) %>
<%= form.text_field(field.name, field.html_options) %>

app/views/forms/_default.html.erb
<% if form_object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(form_object.errors.count, "error") %> prohibited this <%= form_object.model_name.human(count: 1) %> from being saved:</h2>

    <ul>
    <% form_object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% form_object.fields.each do |field| %>
  <div class="field">
    <%= render(partial: field, as: :field, locals: { form: form }) %>
  </div>
<% end %>

<div class="actions">
  <%= form.submit %>
</div>

app/views/forms/default.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.count, "error") %> prohibited this <%= model_name.human(count: 1) %> from being saved:</h2>

    <ul>
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% fields.each do |field| %>
  <div class="field">
    <%= render field, form: form, locals: { form: form } %>
  </div>
<% end %>

<div class="actions">
  <%= form.submit %>
</div>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render_form @idea_form, local: true %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.body %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render_form @idea_form, local: true %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @idea.body %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>